challengegov/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include, re_path
# from mainapp import admin
from graphene_django.views import GraphQLView
# from mainapp.schema import schema
from django.views.decorators.csrf import csrf_exempt

urlpatterns = [
    # path('users/', include('django.contrib.auth.urls')),
    # path('', include('users.urls')),
    # path('admin/', admin.site.urls),
    # path('graphql/', csrf_exempt(GraphQLView.as_view(graphiql=True))),
    # path('accounts/', include('allauth.urls')),
    # path('', include('mainapp.urls')),
    # path('', include('userprofiles.urls')),
    # path('', include('news.urls')),
    # path('newsletter/', include('newsletter.urls')),
    # path('tinymce/', include('tinymce.urls')),
    # re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
]
# handler500 = views.page_500_not_found
handler404 = 'mainapp.views.error_404'
handler500 = 'mainapp.views.error_500'
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path
from . import views
from userprofiles.views import get_user_details

app_name="mainapp"
urlpatterns = [
    path('', views.home, name='homepage'),
    path('allcategories', views.all_categories, name='allcategories'),
    path('search', views.search_results, name='search_results'),
    path('challenges', views.challenges, name='challenges'),
    path('open-challenges', views.open_challenges, name='open-challenges'),
    path('coming-soon', views.coming_soon_challenges, name='coming-soon'),
    path('tags/<int:id>', views.tagged, name='tagged'),
    path('audiences/<int:id>', views.audience_tagged, name='audience-tagged'),
    path('submit-challenge', views.submit_a_challenge, name='submit-a-challenge'),
    path('archived-challenges', views.archived_challenges, name='archived'),
    path('rolling-challenges', views.rolling_challenges, name='rolling'),
    path('detail/<int:id>/<slug:slug>/', views.challenge_detail, name='detail'),
    path('favourite_post/<int:id>/<slug:slug>/', views.favourite_post, name='favourite_post'),
    path('interested/<int:id>/<slug:slug>', views.interested_challenges_list, name='interested-people'),
    path('favourite-challenges', views.favourite_challenge_list, name='favourite-challenges'),
    path('users/<int:id>/', get_user_details, name='the-user'),
    path('about', views.about, name="about"),
    path('privacy-policy', views.privacy_policy, name="privacy_policy"),
]

news/urls.py
from django.urls import path
from . import views

app_name = 'news'
urlpatterns = [
    path('news', views.news_view, name='news'),
    path('news/<int:id>/<slug:slug>/', views.news_details_page, name='details'),
]

userprofiles/urls.py
from django.urls import path
from . import views

app_name='userprofiles'
urlpatterns = [
    path('profile', views.profile, name='profile')
]

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
# from userprofiles.views import get_users_list, get_user_details

app_name = 'users'
urlpatterns = [
    path('accounts/signup/', views.MySignUpView.as_view(), name='account_signup'),
    path('accounts/login/', views.MyLoginView.as_view(), name='account_login'),
    # path('users/list/', get_users_list, name='userlist'),
    # path('users/<int:id>/', get_user_details, name='the-user'),
    ]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
	def __str__(self):
		return self.username

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser
from .countries import COUNTRIES
from django.core.files import File
from PIL import Image
from django import forms
from challengegov import settings


class CustomUserCreationForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super(CustomUserCreationForm, self).__init__(*args, **kwargs)
        self.fields['password1'].help_text = ''
        
    class Meta(UserCreationForm):
        model = CustomUser
        fields = ('username','email',)


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ('username','email',)

users/views.py
from django.urls import reverse_lazy
from django.views import generic
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required #added
# from .forms import UserUpdateForm, ProfileUpdateForm
from .forms import CustomUserCreationForm
from allauth.account.views import SignupView, LoginView


class MySignUpView(SignupView):
    template_name = 'users/signup.html'


class MyLoginView(LoginView):
    template_name = 'registration/login.html'

users/templates/users/email.html
{% extends "mainapp/base.html" %}


{% block content %}
    <h1>E-mail Addresses</h1>
{% if user.emailaddress_set.all %}
<p>{% trans 'The following e-mail addresses are associated with your account:' %}</p>

<form action="{% url 'account_email' %}" class="email_list" method="post">
{% csrf_token %}
<fieldset class="blockLabels">

  {% for emailaddress in user.emailaddress_set.all %}
<div class="ctrlHolder">
      <label for="email_radio_{{forloop.counter}}" class="{% if emailaddress.primary %}primary_email{%endif%}">

      <input id="email_radio_{{forloop.counter}}" type="radio" name="email" {% if emailaddress.primary or user.emailaddress_set.count == 1 %}checked="checked"{%endif %} value="{{emailaddress.email}}"/>

{{ emailaddress.email }}
    {% if emailaddress.verified %}
    <span class="verified">{% trans "Verified" %}</span>
    {% else %}
    <span class="unverified">{% trans "Unverified" %}</span>
    {% endif %}
      {% if emailaddress.primary %}<span class="primary">{% trans "Primary" %}</span>{% endif %}
</label>
</div>
  {% endfor %}

<div class="buttonHolder">
      <button class="secondaryAction" type="submit" name="action_primary" >{% trans 'Make Primary' %}</button>
      <button class="secondaryAction" type="submit" name="action_send" >{% trans 'Re-send Verification' %}</button>
      <button class="primaryAction" type="submit" name="action_remove" >{% trans 'Remove' %}</button>
</div>

</fieldset>
</form>

{% else %}
<p><strong>{% trans 'Warning:'%}</strong> {% trans "You currently do not have any e-mail address set up. You should really add an e-mail address so you can receive notifications, reset your password, etc." %}</p>

{% endif %}


    <h2>{% trans "Add E-mail Address" %}</h2>

    <form method="post" action="{% url 'account_email' %}" class="add_email">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="action_add" type="submit">{% trans "Add E-mail" %}</button>
    </form>

{% endblock %}


{% block extra_body %}
<script type="text/javascript">
(function() {
  var message = "{% trans 'Do you really want to remove the selected e-mail address?' %}";
  var actions = document.getElementsByName('action_remove');
  if (actions.length) {
    actions[0].addEventListener("click", function(e) {
      if (! confirm(message)) {
        e.preventDefault();
      }
    });
  }
})();
</script>
{% endblock %}

users/templates/users/email_confirm.html
{% extends "mainapp/base.html" %}

{% load account %}



{% block content %}
<div class="container">
<h1>Confirm E-mail Address</h1>

{% if confirmation %}

{% user_display confirmation.email_address.user as user_display %}

<p>{% blocktrans with confirmation.email_address.email as email %}Please confirm that <a href="mailto:{{ email }}">{{ email }}</a> is an e-mail address for user {{ user_display }}.{% endblocktrans %}</p>

<form method="post" action="{% url 'account_confirm_email' confirmation.key %}">
{% csrf_token %}
    <button type="submit">{% trans 'Confirm' %}</button>
</form>

{% else %}

{% url 'account_email' as email_url %}

<p>{% blocktrans %}This e-mail confirmation link expired or is invalid. Please <a href="{{ email_url }}">issue a new e-mail confirmation request</a>.{% endblocktrans %}</p>

{% endif %}
</div>
{% endblock %}

users/templates/users/logged_out.html
{% extends "mainapp/base.html" %}
{% load static %}

{% block content %}
<div class="container">
  <br><br><br><br>
  <center>
    <img src="{% static 'img/logo.png' %}" style="width: 150px; height: auto;"class="img-fluid">
  </center>

  <br><br>
  <h3 class="text-center">Sign Out</h3>

  <p class="text-center">Are you sure you want to sign out  ?</p>

  <form method="post" action="{% url 'account_logout' %}">
    {% csrf_token %}
    {% if redirect_field_value %}
    <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}"/>
    {% endif %}
    <center><button type="submit" class="btn btn-success">Yes, I'm signing out</button></center>
  </form>
</div>

{% endblock %}

users/templates/users/password_change.html
{% extends "mainapp/base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Change Password" %}{% endblock %}

{% block content %}
<div class="container">
    <h1>{% trans "Change Password" %}</h1>

    <form method="POST" action="{% url 'account_change_password' %}" class="password_change">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" name="action">{% trans "Change Password" %}</button>
    </form>
  </div>
{% endblock %}

users/templates/users/password_reset_done.html
{% extends "mainapp/base.html" %}

{% load i18n %}
{% load account %}

{% block head_title %}{% trans "Password Reset" %}{% endblock %}

{% block content %}
<div class="container">
    <h1>{% trans "Password Reset" %}</h1>

    {% if user.is_authenticated %}
    {% include "account/snippets/already_logged_in.html" %}
    {% endif %}

    <p>{% blocktrans %}We have sent you an e-mail. Please contact us if you do not receive it within a few minutes.{% endblocktrans %}</p>
  </div>
{% endblock %}

users/templates/users/the_user.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block css %}
{% include 'mainapp/head1.html' %}
{% endblock css %}

{% block content %}
<header class="header-global">
    <nav id="navbar-main" class="navbar navbar-main navbar-expand-lg headroom py-lg-3 px-lg-6 navbar-dark navbar-theme-dark">
        <div class="container">
            <a class="navbar-brand @@logo_classes" href="{% url 'mainapp:homepage' %}">
                <img class="navbar-brand-dark common" src="{% static 'assets/img/logo.png' %}" style="width:200px;height:auto" alt="Logo light">
                <img class="navbar-brand-light common" src="{% static 'assets/img/logo.png' %}" style="width:200px;height:auto" alt="Logo dark">
            </a>
            <div class="navbar-collapse collapse" id="navbar_global">
                <div class="navbar-collapse-header">
                    <div class="row">
                        <div class="col-6 collapse-brand">
                            <a href="{% url 'mainapp:homepage' %}">
                                <img src="{% static 'assets/img/logo.png' %}" style="width:200px;height:auto" alt="Logo Impact">
                            </a>
                        </div>
                        <div class="col-6 collapse-close">
                            <a href="#navbar_global" role="button" class="fas fa-times" data-toggle="collapse"
                                data-target="#navbar_global" aria-controls="navbar_global" aria-expanded="false"
                                aria-label="Toggle navigation"></a>
                        </div>
                    </div>
                </div>
                <ul class="navbar-nav navbar-nav-hover justify-content-center">
                    <li class="nav-item">
                        <a href="{% url 'mainapp:homepage' %}" class="nav-link">Home</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" aria-expanded="false" data-toggle="dropdown">
                            <span class="nav-link-inner-text mr-1" >Challenges</span>
                            <i class="fas fa-angle-down nav-link-arrow" ></i>
                        </a>
                        <div class="dropdown-menu dropdown-menu-lg">
                            <div class="col-auto px-0" data-dropdown-content>
                                <div class="list-group list-group-flush">
                                    <a href="{% url 'mainapp:challenges' %}"
                                        class="list-group-item list-group-item-action d-flex align-items-center p-0 py-3 px-lg-4">
                                        <span class="icon icon-sm icon-black"><i class="fas fa-check-double"></i></span>
                                        <div class="ml-4">
                                            <span class="d-block">All Challenges</span>
                                        </div>
                                    </a>
                                    <a href="{% url 'mainapp:open-challenges' %}" 
                                        class="list-group-item list-group-item-action d-flex align-items-center p-0 py-3 px-lg-4">
                                        <span class="icon icon-sm icon-success"><i
                                                class="fas fa-box-open"></i></span>
                                        <div class="ml-4">
                                            <span class="d-block">Open Challenges</span>
                                        </div>
                                    </a>
                                    <a href="{% url 'mainapp:rolling' %}" 
                                        class="list-group-item list-group-item-action d-flex align-items-center p-0 py-3 px-lg-4">
                                        <span class="icon icon-sm icon-primary"><i
                                                class="fas fa-sync-alt"></i></span>
                                        <div class="ml-4">
                                            <span class="d-block">Open With No Deadline</span>
                                        </div>
                                    </a>
                                    <a href="{% url 'mainapp:coming-soon' %}" 
                                        class="list-group-item list-group-item-action d-flex align-items-center p-0 py-3 px-lg-4">
                                        <span class="icon icon-sm icon-purple"><i
                                                class="far fa-clock"></i></span>
                                        <div class="ml-4">
                                            <span class="d-block">Coming Soon</span>
                                        </div>
                                    </a>
                                    <a href="{% url 'mainapp:archived' %}" 
                                        class="list-group-item list-group-item-action d-flex align-items-center p-0 py-3 px-lg-4">
                                        <span class="icon icon-sm icon-danger"><i
                                                class="fas fa-archive"></i></span>
                                        <div class="ml-4">
                                            <span class="d-block">Archived Challenges</span>
                                        </div>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'mainapp:about'%}" class="nav-link" >About Us</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'news:news'%}" class="nav-link" >News</a>
                    </li>
                    <li class="nav-item">
                    <a href="{% url 'mainapp:submit-a-challenge'%}" target="_blank" class="nav-link"><i class="fas fa-paper-plane mr-2"></i>Submit a Challenge</a>
                    </li>
                    
                    {% if not user.is_authenticated %}
                    <li class="nav-item">
                        <a href="{% url 'users:account_login' %}" class="nav-link" >Login or Register</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a href="{% url 'userprofiles:profile' %}" class="nav-link">Profile</a>
                    </li>
                    <li class="nav-item">
                    <a href="{% url 'account_logout' %}" class="nav-link" >Logout</a>
                    </li>
                    {% endif %}  
                </ul>
            </div>
            <div class="d-flex d-lg-none align-items-center">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar_global"
                    aria-controls="navbar_global" aria-expanded="false" aria-label="Toggle navigation"><span
                        class="navbar-toggler-icon"></span></button>
            </div>
        </div>
    </nav>
</header>

    <main>
        <section class="section-header pb-4 pb-lg-3 mb-0 mb-lg-2 text-white" style="background-image:linear-gradient( #2a0854, #6441a5)">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-12 col-md-8 text-center">
                      <div class="card-profile-image">
                        <div class="rounded-circle" style="max-width: 140px;width:100px;height:100px;border-radius: 0.375rem;border: 3px solid #fff;transform: translate(-50%, -50%) scale(1);position: absolute;left: 50%;transition: all 0.15s ease;background-color:#ed8f03">
                        <span class="text-white" style="display: flex;  justify-content: center; font-size:60px;  align-items: center;">{{avatar_holder}}</span>
                        </div>
                    </div><br><br><br>
                        <h5 class="display-5 pb-2"><i class="fa fa-user"></i>&nbsp;&nbsp;
                          {% if the_user.first_name and the_user.last_name %}
                          {{the_user.first_name}}&nbsp;{{the_user.last_name}}
                          {% else %}
                          {{the_user.user}}
                          {% endif %}
                        </h5>
                        {% if view_contact_info %}
                        <h5 class="display-5 pb-2"><i class="fa fa-envelope"></i>&nbsp;&nbsp;
                          {% if the_user.user.email %}
                          <a href="mailto:{{the_user.user.email}}">{{the_user.user.email}}</a>
                          {% endif %}
                        </h5>
                        <h5 class="display-5 pb-2"><i class="fa fa-briefcase"></i>&nbsp;&nbsp;
                          {% if the_user.organization %}
                          {{the_user.organization }}
                          {% endif %}
                        </h5>
                        {% else %}
                        <h5 class="display-5 pb-2">The user hasn't authorized the viewing of their info</h5>
                        {%endif%}
                    </div>
                </div>
            </div>
        </section>
{% if view_bookmarks %}
<section class="section section-lg bg-soft" style="padding-top:3.5rem!important;">
    <div class="container" style="max-width:1300px;">
      <h3 class="display-3 text-center mt--4">Here are their favourite Challenges</h3>
      {%else%}
<section class="section section-lg bg-white" style="padding-top:3.5rem!important;">
    <div class="container" style="max-width:1300px;">
      <h3 class="display-3 text-center mt--4">Nothing to see here at the moment</h3>
      {%endif%}
        <div class="row">
          {% if view_bookmarks %}
            {% for post in favourite_posts %}
            <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12 card-group">
                <div class="card animate-up-3 mt-5" style="border-radius:15px;">
                    <div class="date" style="background-color:#EE5050; padding:2px 4px; border-radius:5px;position: absolute;top: 14px;left:16px;">
                        {% if post.status == 'Open' %}
                        <span class="day font-weight-bolder text-white">{{post.open_until|timeuntil:post.date_posted}} left</span>
                        {% else %}
                        <span class="day font-weight-bolder text-white">Ongoing</span>
                        {% endif %}
                    </div>
                    <!-- <ul class="menu-content" style="position: absolute;top: 14px;right: 16px;">
                        {% if user.is_authenticated %}
                        {% for cha in post.favourite.all%}
                        {% if cha.username == user.username %}
                        <li>
                            <a class="fas fa-bookmark" style="box-shadow: 0 8px 16px rgba(0, 0, 0, 0.95); color:white"></a>
                        </li>
                        {% endif %}
                        {% endfor %}
                        {% endif %}
                    </ul> -->
                    <a href="{% url 'mainapp:detail' post.id post.slug %}">
                        <img src="{{post.image.url}}" class="card-img-top" style="height:200px;width:100%">
                    </a>
                    <div class="card-body bg-white" style="border-radius:0 0 15px 15px;box-shadow: 0 15px 12px rgba(0, 0, 0, 0.2)">
                        <p><span class="author text-black font-weight-bolder">{{post.offered_by|truncatewords:"3"}}</span>
                            <span class="text-black font-weight-bolder pr-2" style="float:right!important">Status 
                            <span class="badge badge-success badge">
                            {% if post.status == 'Open' %}
                            Open
                            {% else %}
                            Ongoing
                            {% endif %}
                            </span></span>
                        </p>
                        <h5 class="card-title"><a href="{% url 'mainapp:detail' post.id post.slug %}">{{post.title|truncatewords:"5"}}</a></h5>
                        <p class="card-text">{{post.challenge_summary|truncatechars:"150"|safe}}</p>
                        <p class="text-black pt-3 font-weight-bolder"><i class="fas fa-trophy text-brown"></i>&nbsp;{{post.prize|truncatechars:"40"|safe}}</p>
                    </div>
                </div>
            </div>
            {% endfor %}
            {%endif%}
        </div>
    </div>
    <br><br>

</section>
{% endblock content %}

{% block footer %}
<!-- {% include 'mainapp/footer2.html' %} -->
{% endblock footer %}

    </main>

{% block js %}
{% include 'mainapp/head1-bottom.html' %}
{% endblock js %}

users/templates/users/users.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block css %}
{% include 'mainapp/head4.html' %}
{% endblock css %}

{% block content %}
  <nav id="navbar-main" class="navbar navbar-horizontal navbar-transparent navbar-main navbar-expand-lg navbar-light">
    <div class="container">
      <a class="navbar-brand" href="{% url 'mainapp:homepage' %}">
        <img src="{% static 'assets/img/logo.png' %}" style="width:200px; height:auto">
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-collapse" aria-controls="navbar-collapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="navbar-collapse navbar-custom-collapse collapse" id="navbar-collapse">
        <div class="navbar-collapse-header">
          <div class="row">
            <div class="col-6 collapse-brand">
              <a href="{% url 'mainapp:homepage' %}">
                <img src="{% static 'assets/img/logo.png' %}" style="width:200px; height:auto">
              </a>
            </div>
            <div class="col-6 collapse-close">
              <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbar-collapse" aria-controls="navbar-collapse" aria-expanded="false" aria-label="Toggle navigation">
                <span></span>
                <span></span>
              </button>
            </div>
          </div>
        </div>
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a href="{% url 'mainapp:homepage' %}" class="nav-link">
              <span class="nav-link-inner--text">Home</span>
            </a>
          </li>
          <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" aria-expanded="false" data-toggle="dropdown">
                <span class="nav-link-inner-text ">Challenges</span>

            </a>
            <div class="dropdown-menu dropdown-menu-lg">
                <div class="col-auto px-0" data-dropdown-content>
                    <div class="list-group list-group-flush">
                        <a href="{% url 'mainapp:challenges' %}"
                            class="list-group-item list-group-item-action d-flex align-items-center p-0 py-3 px-lg-4">
                            <span class="icon icon-sm icon-success"><i class="fas fa-check-double" style="color:#24262b!important;"></i></span>
                            <div class="ml-4">
                                <span class="text-dark d-block">All Challenges</span>
                            </div>
                        </a>
                        <a href="{% url 'mainapp:open-challenges' %}"
                            class="list-group-item list-group-item-action d-flex align-items-center p-0 py-3 px-lg-4">
                            <span class="icon icon-sm icon-success"><i
                                    class="fas fa-box-open" style="color:#05A677!important;"></i></span>
                            <div class="ml-4">
                                <span class="text-dark d-block">Open Challenges</span>
                            </div>
                        </a>
                        <a href="{% url 'mainapp:rolling' %}"
                            class="list-group-item list-group-item-action d-flex align-items-center p-0 py-3 px-lg-4">
                            <span class="icon icon-sm icon-primary"><i
                                    class="fas fa-sync-alt" style="color:#0648B3!important;"></i></span>
                            <div class="ml-4">
                                <span class="text-dark d-block">Open With No Deadline</span>
                            </div>
                        </a>
                        <a href="{% url 'mainapp:coming-soon' %}"
                            class="list-group-item list-group-item-action d-flex align-items-center p-0 py-3 px-lg-4">
                            <span class="icon icon-sm icon-purple"><i
                                    class="far fa-clock" style="color:#8965e0!important;"></i></span>
                            <div class="ml-4">
                                <span class="text-dark d-block">Coming Soon</span>
                            </div>
                        </a>
                        <a href="{% url 'mainapp:archived' %}"
                            class="list-group-item list-group-item-action d-flex align-items-center p-0 py-3 px-lg-4">
                            <span class="icon icon-sm icon-danger"><i
                                    class="fas fa-archive" style="color:#FA5252!important;"></i></span>
                            <div class="ml-4">
                                <span class="text-dark d-block">Archived Challenges</span>
                            </div>
                        </a>
                    </div>
                </div>
            </div>
          </li>
          <li class="nav-item">
              <a href="{% url 'mainapp:about'%}" class="nav-link" >About Us</a>
          </li>
          <li class="nav-item">
              <a href="{% url 'news:news'%}" class="nav-link" >News</a>
          </li>
          <li class="nav-item">
          <a href="{% url 'mainapp:submit-a-challenge'%}" target="_blank" class="nav-link"><i class="fas fa-paper-plane mr-2"></i>Submit a Challenge</a>
          </li>
          
          {% if not user.is_authenticated %}
          <li class="nav-item">
              <a href="{% url 'users:account_login' %}" class="nav-link" >Login or Register</a>
          </li>
          {% else %}
          <li class="nav-item">
              <a href="{% url 'userprofiles:profile' %}" class="nav-link">Profile</a>
          </li>
          <li class="nav-item">
          <a href="{% url 'account_logout' %}" class="nav-link" >Logout</a>
          </li>
          {% endif %}  
        </ul>
      </div>
    </div>
  </nav>
  <!-- Main content -->
  <div class="main-content" id="panel">

    <!-- Header -->
    <div class="header pb-6" style="background-image: linear-gradient(to right, #1a2a6c, #b21f1f, #fdbb2d);">
        <div class="container-fluid">
            <div class="header-body">
                <div class="row align-items-center py-4"></div>
<div>
<h1 class="display-3 text-white text-center mt-6 mb-3"><b>Users who have Bookmarked this Challenge</b></h1>
</div>
<br>
<br>
        </div>
      </div>
    </div>
    <!-- Page content -->
<div class="container-fluid mt--6">
    <div class="row">
        <div class="col-xl-6">
            <div class="card">
                <div class="card-header border-0">
                </div>
                <div class="pr-4 pl-4 pt-3 pb-5">
                    <h2>{{the_post.title}}</h2>
                    {% for theuser in interested_people %}
                    <p><a href="{% url 'mainapp:the-user' theuser.id %}">
                        {% if theuser.first_name and theuser.last_name %}
                        {{theuser.first_name}}&nbsp;{{theuser.last_name}}
                        {% else %}
                        {{theuser.username}}
                        {% endif %}
                    </a></p>
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="col-xl-3">
            <div class="card">
                <div class="card-header border-0">
                    <p class=" font-weight-bolder">AUDIENCES</p>
                </div>
                <div class="pr-4 pl-4 pb-5 mt--2">
                    {% for audience in ten_audiences %}
                    <a href="{% url 'mainapp:audience-tagged' audience.id %}" class="small" style="background-color: #d1f2ff; padding: 4px 10px; border-radius:5px">{{audience.name}}</a>
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="col-xl-3">
            <div class="card">
                <div class="card-header border-0">
                    <p class=" font-weight-bolder">TAGS</p>
                </div>
                <div class="pr-4 pl-4 pb-5 mt--2">
                    {% for tag in ten_tags %}
                    <a href="{% url 'mainapp:tagged' tag.id %}" class="small text-white" style="background-color: #9461c1; padding: 4px 10px; border-radius:5px">#{{tag.name}}</a>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
      <br>
{% endblock content %}

{% block footer %}
{% include 'mainapp/footer2.html' %}
{% endblock footer %}
    </div>
  </div>

{% block js %}
{% include 'mainapp/head3-bottom.html' %}
{% endblock js %}